### PR TITLE
feat: Makefile and README.md refactored

### PR DESCRIPTION
**Pull request by rajanvalencia**
## Steps
1. Run `make help` for information
2. Run `make install-all OS=macos FONT_NAME=font-hack-nerd-font`
3. Run `make remove-all OS=macos`

##  その他
`make install-all OS=linux FONT_NAME=font-hack-nerd-font` 
と
`make remove-all OS=linux FONT_NAME=font-hack-nerd-font`
の動作は確認していないので編集しといて〜

### CODE REVIEW

**Comment by koiralabishwas** [comment]
issues ::
1. at install-font-linux ()  => I dont know how to automate that too , so lets just add a link to nerdfonts.com
2. at install-zsh-linux (line) =>(apt package manager) apt install only works on ubuntu or debian based linux distros so , it will be better to say ubuntu or debian-distro etc as other linux-distro may not use apt package manager
3. consider deaful shell => most of the linux distro uses bash as a default shell . so , we also need a script to make default shell to zsh if necessary

**Comment by koiralabishwas** [comment]
in 3.
chsh -s $(which zsh) 
(I think system reboot is needed to sync changes)
will make the deaful shell to zsh if user is using bash as default shell

**Comment by koiralabishwas** [comment]
image


i tried it in a new ubuntu and works good
above is the .zsh-config file it created

image

starship is installed as well

**Comment by koiralabishwas** [comment]
I think the only thing remaing is to have a command thad changes the default shell to zsh 



chsh -s $(which zsh)
↑
this will do it in ubuntu systems(reboot required)

**Comment by rajanvalencia** [comment]
> I think the only thing remaing is to have a command thad changes the default shell to zsh
> 
> chsh -s $(which zsh) ↑ this will do it in ubuntu systems(reboot required)

fixed: 0725373

**Comment by koiralabishwas** [comment]
I fixed some minor issues .
packages like fontcache and unzip might not be installed by default in ubuntu systems , so i added the installing commands there

well , thanks verymuch , I leared a lot about making my own install scripts

**Pull request merged**
